Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  config.vm.hostname = "kali"

  # vagrant plugin install vagrant-disksize
  config.disksize.size = "40GB"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 8
    vb.memory = 8192
    vb.gui = false
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision/cui.yml"
  end
end
