Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  # vagrant plugin install vagrant-disksize
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 4096
  end

  config.vm.define "simple" do |server|
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/minimal.yml"
    end
  end

  config.vm.define "ctf" do |server|
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/ctf.yml"
    end
  end
end
