Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # vagrant plugin install vagrant-disksize
  config.disksize.size = "40GB"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 4096
  end

  config.vm.define "simple" do |server|
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/minimal.yml"
    end
  end

  # config.vm.define "docker" do |server|
  #   server.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "provision/docker.yml"
  #   end
  # end

  config.vm.define "ctf" do |server|
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/ctf.yml"
    end
  end
end
